; these shortcuts reset the hotstring mechanism. ~ ensures shortcut is not swallowed
~#lbutton::
~^BACKSPACE::
~+BACKSPACE::
~^DEL::
{
    Hotstring("Reset")
}

; typos
:*?:abbout::about
::abnd::and
::abotu::about
:*?:abouta ::about a
:*?:aboutit::about it
:*?:aboutthe::about the
:*?:aboutt he::about the
:*?:abscence::absence
:*?:accesories::accessories
:*?:acche::cache
:*?:accidant::accident
:*?:accomodate::accommodate
:*?:accordingto::according to
:*?:accross::across
:*?:acheive::achieve
:*?:acheived::achieved
:*?:acheiving::achieving
::acn::can
:*?:acommodate::accommodate
:*?:acomodate::accommodate
:*?:actualyl::actually
:*?:additinal::additional
:*?:additioanl::additional
:*?:addtional::additional
:*?:adequit::adequate
:*?:adequite::adequate
::adn::and
:*?:advanage::advantage
:*?:affraid::afraid
:*?:afterthe::after the
:*?:againstt he::against the
:*?:aganist::against
:*?:aggresive::aggressive
:*?:aggrevate::aggravate
:*?:aggrevated::aggravated
:*?:aggrevates::aggravates
:*?:aggrevating::aggravating
:*?:agian::again
:*?:agreemeent::agreement
:*?:agreemeents::agreements
:*?:agreemnet::agreement
:*?:agreemnets::agreements
:*?:agressive::aggressive
:*?:ahppen::happen
:*?:ahrd::hard
:*?:ahve::have
:*?:allwasy::always
:*?:allwyas::always
:*?:almots::almost
:*?:almsot::almost
:*?:alomst::almost
:?:alot::a lot  ; alotted
:*?:alraedy::already
:*?:alreayd::already
:*?:alreday::already
:*?:altogether::alltogether
:*?:alwasy::always
:*?:alwats::always
:*?:alway s::always
:*?:alwyas::always
:*?:amazinh::amazing
::amde::made
:*?:Ameria::America
:*?:Ameriac::America
::amke::make
::amkes::makes
:*?:ammend::amend
:*?:{Space}amster::{Space}master
:*?:analuyzer::analyzer
:*?:analyuzer::analyzer
::anbd::and
::andone::and one
:*?:ando ne::and one
:*?:andt h e::and the
:*?:andt he::and the
:*?:andteh::and the
:*?:andthe::and the
:*?:anmd::and
::anothe ::another
:*?:anothe r::another{Space} 
:*?:anthing::anything
:*?:antyhing::anything
::anual::annual
:*?:aoppend::append
:*?:apge::page
:*?:apopend::append
:*?:apparant::apparent
:*?:apparrent::apparent
:*?:appearence::appearance
:*?:appeares::appears
:*?:applicaiton::application
:*?:applicaitons::applications
:*?:applyed::applied
:*?:appointiment::appointment
:*?:apprecaited::appreciated
:*?:approrpiate::appropriate
:*?:approrpriate::appropriate
:*?:aquisition::acquisition
:*?:aquisitions::acquisitions
:*?:arguement::argument
:*?:arguements::arguments
:*?:argyument::argument
:*?:argyuments::arguments
::arond::around
:*?:aroudn::around
:*?:artical::article
:*?:articel::article
:*?:asdvertising::advertising
:*?:askt h e::ask the{Space}
::aslo::also
::asthe::as the
::ast he::as the
:*?:atention::attention
:*?:atmospher::atmosphere
::attentioin::attention
::atthe::at the
::att he::at the
:*?:audeince::audience
:*?:audiance::audience
:*?:avaialble::available
:*?:availalbe::available
::awya::away
::aywa::away
:*?:b;;ack::black
:*?:b;ack::black
:*?:bahs::bash
:*?:bakc::back
:*?:balence::balance
:*?:ballance::balance
:*?:baout::about
:*?:bashg::bash
:*?:basgh::bash
:*?:bcak::back
:*?:beacuse::because
:*?:becasue::because
::becaus::because
:*?:becausea::because a
:*?:becauseof::because of
:*?:becausethe::because the
:*?:becauseyou::because you
:*?:becomeing::becoming
:*?:becomming::becoming
:*?:becuase::because
:*?:becuse::because
:*?:befoer::before
:*?:beggining::beginning
:*?:begining::beginning
:*?:beginining::beginning
:*?:beleiev::believe
:*?:beleieve::believe
:*?:beleif::belief
:*?:beleive::believe
:*?:beleived::believed
:*?:beleives::believes
:*?:benifit::benefit
:*?:benifits::benefits
:*?:betwen::between
:*?:beutiful::beautiful
::bew::new
:*?:booknig::booking
::boxs::boxes
:*?:branhc::branch
:*?:brodcast::broadcast
:*?:butthe::but the
::buyt::but
::bvault::vault
::bve::be
::byut::but
::caf::cafe
:*?:caharcter::character
:*?:calcullated::calculated
:*?:calulated::calculated
:*?:campain::campaign
:*?:candidtae::candidate
:*?:candidtaes::candidates
:*?:catagory::category
:*?:categiory::category
:*?:certian::certain
:*?:challange::challenge
:*?:challanges::challenges
:*?:chaneg::change
:*?:chanegs::changes
:*?:changable::changeable
:*?:changeing::changing
:*?:changng::changing
:*?:charachter::character
:*?:charachters::characters
:*?:charactor::character
:*?:charecter::character
:*?:charector::character
:*?:cheif::chief
:*?:chekc::check
:*?:chnage::change
:*?:chruch::church
:*?:cieling::ceiling
:*?:circut::circuit
:*?:claer::clear
:*?:claered::cleared
:*?:claerly::clearly
:*?:cleint::client
:*?:cliant::client
:*?:cliche::cliché
:*?:clickign::clicking
::cloen::clone
:*?:cmae::came
:*?:cna::can
:*?:co[pying::copying
::coint::count
:*?:colection::collection
:*?:comamnd::command
:*?:comanies::companies
:*?:comany::company
:*?:comapnies::companies
:*?:comapny::company
:*?:comaprison::comparison
:*?:combintation::combination
:*?:combnation::combination
:*?:combnations::combinations
:*?:comemnt::comment
:*?:comited::committed
:*?:comittee::committee
:*?:commadn::command
:*?:comming::coming
:*?:commitee::committee
:*?:committe::committee
:*?:committment::commitment
:*?:committments::commitments
:*?:committy::committee
:*?:comntain::contain
:*?:comntains::contains
:*?:compair::compare
:*?:compleated::completed
:*?:compleatly::completely
:*?:compleatness::completeness
:*?:completly::completely
:*?:completness::completeness
:*?:compnay::company
:*?:composate::composite
:*?:comtain::contain
:*?:comtains::contains
:*?:comunicate::communicate
:*?:comunity::community
:*?:condolances::condolences
:*?:conect::connect
:*?:conenct::connect
:*?:conferance::conference
:*?:confirmmation::confirmation
:*?:confliect::conflict
:*?:confliects::conflicts
:*?:considerit::considerate
:*?:considerite::considerate
:*?:consonent::consonant
:*?:conspiricy::conspiracy
:*?:consultent::consultant
:*?:convertable::convertible
:*?:cooparate::cooperate
:*?:cooporate::cooperate
:*?:coount::count
:*?:cop[ying::copying
:*?:corproation::corporation
:*?:corproations::corporations
:*?:corruptable::corruptible
::cotten::cotton
:*?:coudl::could
:*?:couint::count
:*?:couldthe::could the
:*?:couldt he::could the
::cpoy::copy
:*?:ctaegory::category
:*?:cusotmer::customer
:*?:cusotmers::customers
:*?:cutsomer::customer
:*?:cutsomers::customers
:*?:cxan::can
:*?:danceing::dancing
:*?:dcument::document
:*?:deafult::default
:*?:deatils::details
::debuggin::debugging
:*?:decison::decision
:*?:decisons::decisions
:*?:defendent::defendant
:*?:definately::definitely
:*?:deptartment::department
:*?:desicion::decision
:*?:desicions::decisions
:*?:desision::decision
:*?:desisions::decisions
:*?:detente::dent
:*?:develeoprs::developers
:*?:devellop::develop
:*?:develloped::developed
:*?:develloper::developer
:*?:devellopers::developers
:*?:develloping::developing
:*?:devellopment::development
:*?:devellopments::developments
:*?:devellops::develop
::develope::develop
:*?:developement::development
:*?:developements::developments
:*?:developor::developer
:*?:developors::developers
:*?:develpment::development
:*?:diaplay::display
:*?:didnot::did not
:*?:didnt'::didn't
:*?:difefrent::different
:*?:diferences::differences
:*?:differance::difference
:*?:differances::differences
:*?:differant::different
:*?:differemt::different
:*?:differnt::different
:*?:diffrent::different
:*?:dioxine::dioxide
:*?:diplsay::display
:*:directer::director
:*:directers::directors
:*?:directiosn::direction
:*?:disatisfied::dissatisfied
:*?:discoverd::discovered
:*?:disign::design
:*?:dispaly::display
:*?:dissonent::dissonant
:*?:distribusion::distribution
:*?:divsion::division
:*?:docuement::documents
:*?:docuemnt::document
:*?:documetn::document
:*?:documnet::document
:*?:documnets::documents
:*?:doe s ::does{Space}
:*?:doese ::does{Space}
:*?:doesnt'::doesn't
:*?:doign::doing
:*?:doimg::doing
::doind::doing
::dollers::dollars
::donig::doing
:*?:doyuble::double
:*?:driveing::driving
:*?:drnik::drink
:*?:ednoint::endpoint
:*?:ednpoint::endpoint
::efel::feel
::effecient::efficient
::efort::effort
::eforts::efforts
; ::ehr::her
:*?:eligable::eligible
:*?:eligble::eligible
:*?:eligilbe::eligible
:*?:eliglbe::eligible
:*?:elngth::length 
:*?:embarass::embarrass
:*?:Englihs::English
:*?:enought::enough
:*?:entree::entr
:*:env var::environment variable
:*?:environemtn::environment
:*?:equippment::equipment
:*?:equivalant::equivalent
::erbase::rebase
::esle::else
:*?:especialyl::especially
:*?:especialyl::especially
:*?:espesially::especially
:*?:exaplme::example
:*?:excellant::excellent
:*?:excercise::exercise
:*?:exchagne::exchange
:*?:exchagnes::exchanges
:*?:excitment::excitement
:*?:exhcange::exchange
:*?:exhcanges::exchanges
:*?:exmpale::example
:*?:experiance::experience
::experienc::experience
:*?:exprience::experience
:*?:exprienced::experienced
:*?:exzport::export
::eyt::yet
:*?:ezxport::export
:*?:faeture::feature
:*?:faetures::features
:*?:familair::familiar
:*?:familar::familiar
:*?:familliar::familiar
:*?:fammiliar::familiar
:*?:feild::field
:*?:feilds::fields
:*?:feixtures::fixtures
:*?:fianlly::finally
:*?:fidn::find
::fiel::file
::fiels::files
:*?:finallty::finally
:*?:finalyl::finally
:*?:firends::friends
::firts::first
:*?:fklake8::flake8
:*?:flake78::flake8
:*?:flake87::flake8
:*?:folloiwng::following
:*?:follwo::follow
:*?:follwoing::following
::fora::for a
:*?:foriegn::foreign
:*?:forieng::foreign
:*?:forigen::foreign
:*?:forthe::for
:*?:forwrd::forward
:*?:forwrds::forwards
:*?:foudn::found
:*?:foward::forward
:*?:fowards::forwards
:*?:freind::friend
:*?:freindly::friendly
:*?:freinds::friends
:*?:frmo::from
; ::fro::for becaue I type "fro m" a lot and that becomes "ffor" for some reason
:*:fro m::from{Space}
:*?:fromthe::from the
:*?:fromt he::from the
:*?:furneral::funeral
::fwe::few
:*?:garantee::guarantee
:*?:gaurd::guard
::gdo::god
:*?:gemeral::general
:*?:gerat::great
:*?:geting::getting
::gettin::getting
:*?:ghard::hard
:*?:gi5t::git
::gity::git
:*?:gievn::given
:*?:giit::git
::gile::file
::giot::git
:*?:giveing::giving
:*?:gloabl::global
:*?:goign::going
:*?:goit::git
:*?:gonig::going
:*?:govenment::government
:*?:goverment::government
:*?:gruop::group
:*?:gruops::groups
:*?:grwo::grow
:*?:guidlines::guidelines
:*?:guit::git
:*?:hadbeen::had been
:*?:haev::have
:*?:hanlded::handled
::hapen::happen
:*?:hapened::happened
:*?:hapening::happening
:*?:hapens::happens
:*?:happend::happened
:*?:hasbeen::has been
:*?:havebeen::have been
:*?:haveing::having
::hda::had
:*?:hearign::hearing
:*?:helpfull::helpful
:*?:herat::heart
:*?:hesaid::he said
:*?:hewas::he was
:*?:hge::he
:*?:hicchoughs::hiccoughs
:*?:hismelf::himself
:*?:hlep::help
:*?:hopefulyl::hopefully
::hsa::has
::hsi::his
::hte::the
:*?:htere::there
:*?:htese::these
:*?:htey::they
:*:hting::thing
:*?:htink::think
:*?:htis::this
:*?:hvae::have
:*?:hvaing::having
:*?:hwich::which
:*?:idae::idea
:*?:idaes::ideas
:*?:identofy::identify
::ifle::file
::ihs::his
:*?:imediate::immediate
:*?:imediatly::immediately
:*?:immediatly::immediately
:*?:importent::important
:*?:importnat::important
:*?:impossable::impossible
:*?:impotr::import
:*?:improt::import
:*?:improvemnt::improvement
:*?:improvment::improvement
::includ::include
:*?:inconsitency::inconsistency
:*?:inconsitent::inconsistent
:*?:indecate::indicate
:*?:indenpendence::independence
:*?:indenpendent::independent
:*?:indepedent::independent
:*?:independance::independence
:*?:independant::independent
:*?:influance::influence
:*?:infomation::information
:*?:informatoin::information
:*?:inital::initial
:*?:inlcudes::includes
:*?:instaleld::installed
:*?:insted::instead
:*?:instruciton::instruction
:*?:instrucitons::instructions
:*?:insurence::insurance
:*?:int h e::in the
:*?:int he::in the
::interum::interim
::inthe::in the
:*?:invioce::invoice
:*?:invocie::invoice
:*?:inwhich::in which
:*?:ionstance::instance
:*?:iqniry::inquiry
:*?:iqnuiry::inquiry
:*?:isntall::install
:*?:isnstall::install
:*?:isntead::instead
::ither::either
::itis::it is
:*?:ititial::initial
:*?:itnerest::interest
:*?:itnerested::interested
:*?:itneresting::interesting
:*?:itnerests::interests
:*?:itwas::it was
::iwll::will
::iwth::with
::jsut::just
:*?:jugment::judgment
:*?:knowldge::knowledge
:*?:knowlege::knowledge
::knw::know
:*?:knwo::know
:*?:knwon::known
:*?:knwos::knows
:*?:konw::know
:*?:konwn::known
:*?:konws::knows
:*?:labratory::laboratory
:*?:laready::already
:*?:lastyear::last year
::launc::launch
:*?:launcj::launch
:*?:learnign::learning
:*?:lenght::length
:*?:lerave::leave
:*?:levle::level
:*?:libary::library
:*?:librarry::library
:*?:librery::library
::liek::like
; :*?:liekd::liked ; went wrong when typed `liekd + space` for some reason
:*?:lieutenent::lieutenant
::liev::live
:*?:ligth::light
:*?:likly::likely
:*:lisense::license  ; counterexample: intellisense
:*?:littel::little
:*?:litttle::little
:*?:liuke::like
:*?:liveing::living
::loev::love
::lonly::lonely
:*?:lookign::looking
:*?:maintenence::maintenance
:*?:makeing::making
:*?:managment::management
:*?:mantain::maintain
:*?:marraige::marriage
:*?:meessage::message
::megre::merge
:*?:memeber::member
:*?:menaing::meaning
:*?:merchent::merchant
:*?:mesage::message
:*?:mesages::messages
:*?:mispell::misspell
:*?:mispelling::misspelling
:*?:mispellings::misspellings
:*?:mkae::make
:*?:mkaes::makes
:*?:mkaing::making
:*?:moeny::money
:*?:mohter::mother
:*?:morgage::mortgage
:*?:motorcyckle::motorcycle
:*?:motorcyucle::motorcycle
::mroe::more
:*?:mysefl::myself
::myu::my
:*?:naother::another
:*?:necassarily::necessarily
:*?:necassary::necessary
:*?:neccessarily::necessarily
:*?:neccessary::necessary
:*?:necesarily::necessarily
:*?:necesary::necessary
:*?:negotiaing::negotiating
:*?:nkow::know
:*?:nmae::name
:*?:nothign::nothing
:?:nver::never
::nwe::new
::nwo::now
:*?:obediant::obedient
:*?:ocasion::occasion
:*?:occassion::occasion
:*?:occassionally::occasionally
:*?:occured::occurred
:*?:occurence::occurrence
:*?:occurrance::occurrence
:*?:ocur::occur
:*?:oeprator::operator
:*:ofits::of its
:*?:ofi ts::of its
::ofr::for
::oging::going
::ohter::other
:*?:ohterwise::otherwise
::omre::more
::oneof::one of
::onepoint::one point
:*?:onlien::online
:*?:ont he::on the
:*?:ont h e::on the
::onyl::only
:*?:opneing::opening
:*?:oppasite::opposite
:*?:opperation::operation
:*?:oppertunity::opportunity
:*?:opposate::opposite
:*?:opposible::opposable
::opposit::opposite
:*?:oppotunities::opportunities
:*?:oppotunity::opportunity
:*?:opython::python
:*?:orginization::organization
:*?:orginized::organized
:*?:otehr::other
:*?:otpions::options
::otu::out
:c*:outof::out of
:*?:overthe::over the
:*?:owrk::work
:*?:owuld::would
:*?:oxident::oxidant
:*?:papaer::paper
:*?:parliment::parliament
:*?:partof::part of
:*?:patsh::paths
:*?:paymetn::payment
:*?:paymetns::payments
:*?:pciture::picture
:*?:peice::piece
:*?:peices::pieces
:*?:peoetry::poetry
:*?:peoetryy::poetry
:*?:peolpe::people
:*?:peopel::people
:*?:peoptry::poetry
:*?:peorty::poetry
:*?:peotry::poetry
:*?:pioetry::poetry
:*?:percentof::percent of
:*?:percentto::percent to
:*?:performence::performance
:*?:perhasp::perhaps
:*?:perhpas::perhaps
:*?:permanant::permanent
:*?:perminent::permanent
:*?:personalyl::personally
:*?:placehodler::placeholder
::pleas::please
:*?:pleasent::pleasant
:*?:poath::path
:*?:poeple::people
:*?:poerty::poetry
:*?:poertyy::poetry
:*?:poeryt::poetry
:*?:poeryty::poetry
:*?:porblem::problem
:*?:porblems::problems
:*?:porvide::provide
:*?:possable::possible
:*?:postition::position
:*?:potentialy::potentially
:*?:practisch::praktisch
:*?:pregnent::pregnant
:*?:presance::presence
:*?:pretrty::pregnant
:*?:prevenmts::prevents
:*?:probelm::problem
:*?:probelms::problems
:*?:prominant::prominent
:*?:protocal::protocal
:*?:protofub::protobuf
:*?:psoition::position
:*?:ptogress::progress
:*?:pukll::pull
::puting::putting
:*?:pwoer::power
:*?:pythin::python
:*?:pythoni::python
::pyton::python
:*?:qeustion::question
:*?:qeustions::questioins
::quater::quarter
:*?:quaters::quarters
:*?:quesion::question
:*?:quesions::questions
:*?:questioms::questions
:*?:questiosn::questions
:*?:questoin::question
:*?:quetion::question
:*?:quetions::questions
:*?:readonlyu::readonly
:*?:realyl::really
:*?:reaplce::repalce
:*?:reccomend::recommend
:*?:reccommend::recommend
:*?:receieve::receive
:*?:recieve::receive
:*?:recieved::received
:*?:recieving::receiving
:*?:recomend::recommend
:*?:recomendation::recommendation
:*?:recomendations::recommendations
:*?:recomended::recommended
:*?:reconize::recognize
:*?:recrod::record
:*?:refering::referring
:*?:registery::registry
:*?:reinstante::reinstate
:*?:relavtivity::relativity
:*?:religous::religious
:*?:relkativity::relativity
:*?:reluctent::reluctant
:*?:remeber::remember
:*?:reommend::recommend
:*?:repalce::replace
:*?:reprentation::representation
:*?:representativs::representatives
:*?:representives::representatives
:*?:represetned::represented
:*?:represnt::represent
:*?:requets::request
:*?:requirment::requirement
:*?:requirments::requirements
:*?:reserach::research
:*?:resollution::resolution
:*?:resorces::resources
:*?:respomd::respond
:*?:respomse::response
:*?:responce::response
:*?:responsability::responsibility
:*?:responsable::responsible
:*?:responsibile::responsible
:*?:responsiblity::responsibility
:*?:resposne::response
:*?:restaraunt::restaurant
:*?:restuarant::restaurant
:*?:resuylt::result
:*?:resyult::result
:*?:retyrn::return
:*?:retunr::return
:*?:dahsbo::dashbo::
:*?:retyurn::return
:*?:reult::result
:*?:reveiw::review
:*?:reveiw::review
:*?:reveiwed::reviewed
:*?:reveiwing::reviewing
:*?:rumers::rumors
:*?:rwite::write
:*?:rythm::rhythm
:*?:saidhe::said he
:*?:saidit::said it
:*?:saidt h e::said the
:*?:saidthat::said that
:*?:saidthe::said the
:*?:scedule::schedule
:*?:sceduled::scheduled
:*?:scenarioes::scenarios
:*?:secratary::secretary
:*?:sectino::section
:*?:seesion::session
::seh::she
:*?:selectoin::selection
:*?:sentance::sentence
:*?:separeate::separate
:*?:seperate::separate
:*?:sercumstances::circumstances
:*?:sevral::several
:*?:shcool::school
:*?:shesaid::she said
:*?:shfit::shift
:*?:shineing::shining
:*?:shiped::shipped
:*?:shotr::short
:*?:shotrly::shortly
:*?:shoudl::should
:*?:shoulnd't::shouldn't
:*?:showinf::showing
:*?:signifacnt::significant
:*?:significatn::significant
:*?:simalar::similar
:*?:similiar::similar
:*?:simplfiy::simplify
:*?:simpyl::simply
:*?:sincerly::sincerely
:*?:sitll::still
::smae::same
:*?:smaple::sample
::smoe::some
::soem::some
:*?:soemthing::something
::sohw::show
::soical::social
:*?:somehwere::somewhere
:*?:somethign::something
:*?:someting::something
:*?:somewaht::somewhat
:*?:somthing::something
:*?:somtimes::sometimes
:*?:somwehere::somewhere
::sot hat::so that
:*?:soudn::sound
:*?:spanaird::spaniard
:*?:speach::speech
:*?:specatime::spacetime
:*?:specificaly::specifically
:*?:specificalyl::specifically
:*?:statment::statement
:*?:statments::statements
:*?:stnad::stand
:*?:stopry::story
:*?:stoyr::story
::stpo::stop
:*?:strentgh::strength
:*?:strets::streets
:*:stroy::story  ; destroy
:*?:struggel::struggle
:*?:strugle::struggle
:*?:studnet::student
:*?:suage::usage
:*?:sublclass::subclass
:*?:succesful::successful
::successfull::successful
:*?:successfuly::successfully
:*?:successfulyl::successfully
:*?:sucess::success
:*?:sucessfull::successful
:*?:Sudnay::Sunday
:*?:sufficiant::sufficient
:*?:suggesiton::suggestion
:*?:suggesitons::suggestions
:?:suggestin::suggestion
:*?:suggestins::suggestions
:*?:suggestins::suggestions
:*?:suggestoin::suggestion
:*?:suggestoins::suggestions
:*?:suggeston::suggestion
:*?:suposed::supposed
:*?:suppoesd::supposed
:*?:suppossed::supposed
:*?:suprise::surprise
:*?:suprised::surprised
:*?:swiming::swimming
:*?:swqing::swing
:*?:sybntax::syntax
:*?:synbtax::syntax
:*?:tahank::thank
:*?:tahanks::thanks
::tahn::than
::tahnk::thank
::tahnks::thanks
::taht::that
:*?:takign::taking
:*?:talekd::talked
:*?:talkign::talking
::tath::that
:*?:taylored::tailored
:*?:tecnical::technical
::teh::the
::tehy::they
::tellt he::tell the
:*?:tempalte::template
:*?:termoil::turmoil
::tghe::the
:*?:tghis::this
::thak::thank
:*?:thakns::thanks
:*?:thaks::thanks
:*?:thansk::thanks
::thatt he::that the
::thatthe::that the
:*?:thecompany::the company
:*?:thefirst::the first
:*?:thegovernment::the goverment
:*?:themself::themselves
:*?:themselfs::themselves
:*?:thenew::the new
:*?:there\s ::there's
::theri::their
:*?:thesame::the same
::thet teh::that the
:*?:thetwo::the two
:*?:thgat::that
:*?:thge::the
:*:thier::their
:*?:thigsn::things
:*?:thisyear::this year
:*?:thna::than
:*?:thne::then
:*?:thnig::thing
:*?:thnigs::things
:*?:threatend::threatened
::thsi::this
:*?:thsoe::those
::tht::that
::thta::that
:*?:thye::they
::tihs::this
:*?:timetsamp::timestamp
:*?:timne::time
:*?:tiogether::together
::tje::the
:*?:tjhe::the
:*?:tkae::take
:*?:tkaes::takes
:*?:tkaing::taking
:*?:tlaking::talking
:*?:todaty::today
:*?:todayt::today
:*?:todya::today
:*?:togehter::together
:*?:tokesn::tokens
:*?:toldt he::told the
:*?:tomorow::tomorrow
:*?:tongiht::tonight
:*?:tonihgt::tonight
::totaly::totally
:*?:totalyl::totally
:*?:tothe::to the
:*?:towrad::toward
:*?:traditionalyl::traditionally
:*?:transfered::transferred
:*?:translatoin::translation
:*?:tresure::treasure
:*?:tresured::treasured
:*?:truely::truly
:*?:truley::truly
:*?:tryed::tried
:*?:tsaj::tsja
:*?:tthe::the
::ture::true
:*?:tyhat::that
:*?:tyhe::the
:*?:udnerstand::understand
:*?:understnad::understand
:*?:undert he::under the
:*?:UnitedStates::United States
:*?:uniwp::unwip
:*?:unliek::unlike
:*?c:untill::until  ; in C#: untilLast shouldn't be autocorrected
::untitest::unittest
::unti test::unit test
:*?:useing::using
:*?:usualyl::usually
:*?:varaible:::variable
:*?:varaible::variable
:*?:varianble::variable
:*?:veyr::very
:*?:virtualyl::virtually
:*?:vrey::very
:*?:vulnerible::vulnerable
:*?:wa s ::was{Space}
:*?:waht::what
:*?:warrent::warrant
:*?:wasnt'::wasn't
:*?:wathc::watch
:*?:wathcing::watching
::watn::want
::wehn::when
::werre::were
:*?:whcih::which
:*?:wherre::where
:*?:whethre::whether
::whic::which
:*?:whicht he::which the
:*?:whiel::while
:*?:whihc::which
:*?:whta::what
:*?:wiatress::waitress
:*?:wief::wife
:*?:wierd::weird
:*?:wihch::which
:*?:wiht::with
:*?:willbe::will be
:*?:windoes::windows
:*?:witha::with a
:*?:withe::with
:*?:witht he::with the
:*?:withthe::with the
:*?:wiull::will
:*?:wnat::want
:*?:wnated::wanted
:*?:wnats::wants
:*?:woh::who
:*?:wohle::whole
:*?:wokr::work
:*?:workign::working
:*?:woudl::would
:*?:wouldbe::would be
::wriet::write
:*?:writting::writing
:*?:wrod::word
::wroet::wrote
:*?:wroking::working
:*?:wtih::with
:*?:wuould::would
:*?:wya::way
:*?:yera::year
:*?:yeras::years
:*?:yersa::years
:*?:yoiu::you
:*?:yoru::your
:*?:youer::your
:*?:your're::you're
:*?:ytou::you
::yuo::you
:*?:yuor::your
:*?:hakon::håkon
:*?:self driven::self-driven
:c:Remin::ReMin
:c:Github::GitHub
:*?:moemen::momen
:*?:moemnt::moment
:*?:fitler::filter
:*?:pattenr::pattern
:*?:becayuse::because
:*?:abuot::about
::suych::such
::beewn::been
:*?:gmamil::gmail
:*?:gmial::gmail
:*?:ppoetry::poetry
:*?:hjard::hard
:*?:beautifil::beautiful
:*?:directroy::directory
::I'm guess::I'm guessing 
::pyton::python
::pytohn::python
::parkting::parking
:*?:restatr::restart
:*?:wqhich::which
:*?:runnign::running
:*?:isseu::issue
:*?:extensino::extension
:*?:froatm::format
::pyll::pull
::mypy.::mypy .
::cluod::cloud
:*?:pigguback::piggyback
:*?:soruce::source
:*?:nothnig::nothing
:*?:inlcuding::including
:*?:optinoal::optional
::rebae::rebase
:*?:udpate::update
::omfr::from
::fronm::from
:*?:proeprt::propert
::psuh::push
:*?:environemtn::environment
:*?:environemnt::environment
::incrase::increase
:*?:coutn::count
::upruising::uprising
::woulnd't::wouldn't
::unwiop::unwip
::unqiop::unwip
::unqip::unwip
::gatewat::gateway
:*?:couldnt'::couldn't
::resistent::resistant
:*?:enpoint::endpoint
::midn::mind
::wchih::which
::scritp::script
::visibie::visible
::visibile::visible
::lsit::list
:*?:udnerstood::understood
:*?:lcoalhost::localhost
:*?:localhiost::localhost
::frist::first
::proemtheos::prometheus::
::promethues::prometheus::
::proemtheus::prometheus::
::brnach::branch
:*?:localhjost::localhost
:*?:exprort::export
:*?:promentheus::prometheus
:*?:backsapce::backspace
:*?:Deepinisght::Deepinsight
:*?:udner::under
::toyen::Tøyen
::therefor::therefore
:*?:thorugh::through
:*?:visisb::visib
:*?:constratin::constraint
::reuslt::result
:*?:unmder::under
:*?:puybli::publi
::csporj::csproj
::emssage::message
::mesaage::message
::expcetion::exception
:*?:buidl::build
::eixt::exit
::kidn::kind
::wamr::warm
:*?:stahs::stash
:*?:gituhb::github
:*?:elemetn::element
:*?:specifeid::specified
:*?:giut::git::
:*?:dontet::dotnet
::tiem::time
:*?:runtiem::runtime
:*?:nubmer::number
:*?:dinstance::distance
:*?:epxect::expect
:*?:ionstall::install
:*?:configruation::configuration
:*?:refernen::referen
:*?:gronnerlokka::Grünnerløkka
:*?:grunnerlokka::Grünnerløkka
:*?:tutoriual::tutorial
:*?:plygin::plugin
:*?:plyugin::plugin
:*?:satsh::stash
:*?:optiosn::options
::lcoal::local
::dwebug::debug
:*?:flaot::float
:*?:crtitical::critical
:*?:termainl::terminal
:*?:branc h::branch{Space}
:*?:boundign::bounding
::unwuip::unwip
:*?:idnex::index
::liens::lines
::strign::string
:*?:docyum::docum
:*?:aiton:ation
::asert::assert
::luinq::linq
:*?:speical::special
:*?:gothub::GitHub
::Scicily::Sicily
:*?:ptyhon::python
:*?:functinos::functions
:*?:semgnet::segment
:*?:dokc::dock
:*?:contenst::contents
:*?:supress::suppress
:*?:deskotp::desktop
:*?:asycn::async
:*?:struing::string
:*?:isntead::instead
::gfit::git
:*?:hieght::height
:*?:cosnt::const
:*?:asybnc::async
; :*?:retuirn::return ; doesn't work: 'return' is a keyword in this context
:*?:elemnet:element
:*?:deaful::defaul
:*?:inptu::input
:*?:contineu::continue
:*?:enginieer::engineer
:*?:scriptr::script
::converage::coverage
:*?:intsall::install
::alst::last
:*?:datetiem::datetime
:*?:inifinity::infinity
:*?:configureati::configurati
:*?:configuratei::configurati
:*?:fropm::from
:*?:curoser::cursor
:*?:fucnt::funct
:*?:selkf::self
:*?:seklf::self
:*?:tyipcal::typical
:*?:typuical::typical
:*?:itner::inter
:*?:druation::duration
:*?:Havard::Håvard
:*?:enuemr::enumer
::Jorgen::Jørgen
:*?:emergerncy::emergency
:*?:formatino::formation
:*?:contenxt::context
:*?:contentx::contexts
:*?:ppublic::public
::elave::leave
:*?:specifiy::specify
:*?:specialities::specialties
:*?:speciality::specialty
:*?:existince::existence
:*?:as7ync::async
:*?:fethc::fetch
:*?:constriant::constraint
:*?:depatr::depart
:*?:cateory::category
:*?:cateopry::category
:*?:argumetns::arguments
:*?:stasgh::stash
:*?:encoujnter::encounter
:*?:balzor::blazor
:*?:.sjon::.json
:*?:dispaly::display
:*?:pacakage::package
:*?:psotgres::postgres
:*?:apepd::apped
:c*:GHIR::FHIR
:*?:gemenet::gement 
:*?:multple::multiple
:*?:domaion::domain
:*?:javscript::javascript
:*?:undefiend::undefined
:*?:wanring::warning
:*?:polyfon::polygon
:*?:poitn::point
:*?:vscoed::.vscode
:*?:vsocde::.vscode
:*?:vsoced::.vscode
:*?:sandwhich::sandwich
:*?:interger::integer
::thr::the
::qlosing::closing
::fo::of
; because of bash we do a bit different here:
:*?: fi ::{Space}if{Space}
:*?:gogole::google
:*?:isntan::instan
:*?:boudn::bound
:*?:oundign::ounding
:*?:cvolumn::column
:*?:refernc::referenc
:c*:IENum::IEnum
:c*:contraint::constraint
:c*:interal::internal
:*?:tehj::the
:*?:stallaing::stalling
:*?:thrusday::thursday
:*?:deepinsigth::deepinsight
:*?:toosl::tools
:*?::whijch::which
::biug::big
::scipt::script
:*?:thecnic::technic
::deson't::doesn't
::lien::line
:*?:naem::name
:*?:ubutnu::ubuntu
:*?:frogot::forgot
:*?:konjhem::konhjem::
:*?:isnight::insight
:*?:becvause::because
:*?:fragame::fragme
:*?:frageme::fragme
:*?:serivce::service
:*?:stirng::string
:*?:orable::oracle
:*?:oravle::oracle
:*?:up[date::update
:?:hwat::what
:?:ionm::in
:?*:ptyrhon::python
:?*:defintion::definition
:?*:builkd::build
:?*:chidl::child
:?*:glifhht::flight
:?*:glifht::flight
::dont'::don't
:?*:sometyhing::something
:?*:marketplce::marketplace
::parquert::parquet
:?*:impelment::implement
:?*:pytrhon::python
:?*:opinjg::oping
:?*:remvoe::remove
:?*:balck::black
:?*:termianl::terminal
:?*:doptnet::dotnet
:?*:versuion::version
:?*:layopuot::layout
:?*:differenlty::differently
:?*:numbner::number
:*:foten::often
:?*:pacakge::package
:*:trest::test
:*?:rebaes::rebase
:*:evenign::evening
:*?:elegible::eligible
:*?:synontym::synonym
:*?:dictinoary::dictionary  
:*?:compilcate::complicate
:*?:optionla::optional
:*?:negociat::negotiat
:*?:differnet::different
:*?:vertif::certif
::doucle::double
:*?:itneg::integ
; :*?:!+::!=
:*:tyhing::thing
:*?:typuing::typing
:*?:rwebase::rebase
::lcuk::luck
:*:talbe::table
:*?:unipw::unwip
::friom::from
:*?:tierator::iterator
:*?:fliught::flight
:*?:flihgt::flight
::fior::for
:*?:descritpor::descriptor
:*?:descriptro::descriptor
:*?:happesn::happens
:*?:flgith::flight
:*?:valiue::value
:*?:valuie::value
:*?:elswh::elsewe
:*?:compelt::complet
:*?:pythoin::python
::reawd::read
:*?:thruogh::through
:?:programminag::programming
:?*:intergration::integration
:*?:assumilate::assimilate
:*?:assimiluate::assimilate
:*?:assimulate::assimilate
:*?:assumilate::assimilate
:*?:certficate::certificate
:*?:implemention::implementation
:*?:closign::closing
:*?:certifiate::certificate
:*?:conatiner::container
:*?:helath::health
:*?:surpress::suppress
:*?:enthousiastic::enthusiastic
:*?:swithc::switch
:*?:striubng::string
:*?:directoary::directory
:*?:alitry::ality
:*?:fioxes::fixes
:*?:documenation::documentation
:*?:thying::thing
:*?:suirpris::surpris
:*?:chagne::change
:*?:boecjt::object
::asnd::and
:*?:identifer::identifier
:*?:identifer::identifier
:*?:siwthc::switch
:*?:invetiga::investiga
:*?:implemenet::implement
:*?:enojy::enjoy
:*?:tracjker::tracker
:*?:trascker::tracker
:*?:betetr::better
:*?:exceptoin::exception
:*?:retyrb::return
:*?:fxiture::fixture
:*?:righgt::right
:*?:shortbut::shortcut
:*?:hostring::hotstring
:*?:tehcni::techni
::auther::author
:*?:resuilt::result
:?:interpet::interpret
:*?:interpert::interpret
:*?:authoer::author
:*?:usaer::user
:*?:requrie::require
:*?:reqyuire::require
:*?:serevr::server
:*?:presumbably::presumably
:*?:presumbaly::presumably
:*?:elemenet::element
:*?:telementry::telemetry
:*?:telemtry::telemetry
:*?:tonigiht::tonight
:*?:verifiy::verify
:*?:codwes::codes
:*?:duscuss::discuss
:*?:curretn::current
:?:happes::happens
:*?:happesn::happens
:?:happsn::happens
:?*:sessino::session
:*:ghas::has
:*:hgas::has
:*?:uopdate::update
:*?:upodate::update
:*:iump::imp
:*?:instnac::instanc
:*?:senstive::sensitive
:*?:ecxl::excl
::froim::from
:*?:vooid::void
:*?:dopcum::docum
:*?:htrml::html
:?:interla::internal  ; interlaced
:*?:interlan::internal
:*?:pushg::push
:*?:vbalue::value
:*?:develoepr::developer
:*:eome::some
:*?:docuemt::document
:*?:runtime::runtime
:*?:didn';t::didn't
:*?:don';t::don't
:*?:won';t::won't
:*?:linxu::linux
:*?:argumetn::argument
:*?:lokcer::locker
:*?:frive::drive
:*?:baord::board
:*?:lewngth::length
:*?:downloda::download
:*?:uploda::upload
:?:tiosn::tions
::alogn::along
::thrid::third
:*?:obviuos::obvious
:*?:rahter::rather
:*?:rnage::range
:*?:usiong::using
:*?:isntr::instr
:*?:divice::device
:?:aiton::ation
:?:logn::long
:*?:apttern::pattern
:*?:unsire::unsure
:*:dicates::dictates  # e.g. indicates
:*?:chroem::chrome
:*?:mign::ming
:*?:resistably::resistibly
:?:repositry::repository
:*?:thaty'::that'
:?:trian::train
:*:relaly::really
:*?:usiung::using
:*?:usuing::using
:*?:toutori::tutori
::persistne::persistent
::mena::mean
:?*:artificat::artifact
:c:si::is
:*?:resposible::responsible
:*?:resposn::respons
:*?:responsbi::responsib
:?:lsit::list
:*?:opther::other
:*?:mutliple::multiple
:*?:multuiple::multiple
:*?:columsn::columns
:?:tiung::ting
:*?:applca::applica
::lijke::like  ; because of dutch moeilijke/lijken
:*?:pythonnc::pythonic
:*:consise::concise
:*:wign::wing
:?:nign::ning
:*?:hign::hing
:?*:rioght::right
::yhe::the
:*?:explaning::explaining
:*?:deosn'::deosn'
:*?:deosnt'::doesn't
:*?:extneison::extension
:*?:stoppoed::stopped
:*?:mroning::morning
:*?:enjoyt::enjoy
::sefl::self
::ibn::in
:*?:covner::conver
:*?:opnes::ones
::raose::raise
:*?:proejct::project
::ti::it
:*?:valuwe::value
:*?:vlaue::value
:*?:valyuke::value
:*?:funcion::function
::hooby::hobby
:?:tyion::tion
::th3e::the
:*?:luyck::luck
:*?:isnert::insert
:*?:bugfux::bugfix
:*?:fyunc::func
:*?:impliuc::implic
:*?:consuem::consume
::procted::protected
:*?:retuyrn::return
:?:ibng::ing
:*:thjis::this
:*?:intergra::integra
:*?:intepret::interpret
:*?:reuslt::result
:*?:Inteprret::interpret
:?:ioanry::ionary
:?:apeed::apped
:*:kleng::leng
:*?:valuye::value
:*?:swtic::switc
:*?:flopat::float
:*?:inpuit::input
:*?:youi'::you'
::evne::even
::hoep::hope
:*?:pritn::print
:*?:emamil::email
:*?:outptu::output
:*?:inptu::input
:*?:suppoed::supposed
:*?:whjic::whic
:?:mebnt::ment
:*?:assistence::assistance
:*:tehter::tether
:*?:prhas::phras
:*?:difer::differ
:*:ciscum::circum
:*?:staed::stead
:*?:deosn::doesn
:*?:doens'::doesn'
:*?:concernced::concerned
:*?:debyug::debug
:*?:debuyg::debug
:*?:pathc::patch
:*?:enoguh::enough
:*?:unctoin::unction
:*?:ealtch::ealthc
:?:atoin::ation
:?*:desparate::desperate
:*?:motnh::month
:*?:abouot::about
:*?:takling::talking
:?:kgin::king
::tehre::there
:*?:inoal::ional
:*?:luc k::luck{Space}
:*?:morngin::morning
:*?:morningh::morning
:*?:scenaroi::scenario
:*?:drpo::drop
:*?:everthi::everythi
:*?:npote::note
:*:aksed::asked
::baesd::based
:?*:ficture::fixture
:*?:versoin::version
:*?:extne::exten
:*?:seocnd::second
:*?:blakc::black
:*?:shortbut::shortcut
:*?:shortvut::shortcut
:*?:turotial::tutorial
:*?:exaclty::exactly
:*?:alloewd::allowed
:*?:quetsi::questi
:*?:checlist::checklist
:*?:emial::email
:*?:I\'m::I'm
:*?:it\'s::it's
:*?:you\'::you'
:*?:suddenyl::suddenly
::goota::gotta
:*?:consdier::consider
::ot::to
:*?:resukl::resul
:*?:pytonh::python
:*?:furthre::further
::clal::call
:?*:entoin::ention
; :?*:entoins::entions
:*?:actoin::action
; :*?:actoins::actions
:?*:occuring::occurring
:*?:concious::conscious
:*?:concsious::conscious
:*?:vulcano::volcano
:*?:hierarcy::hierarchy
:*?:tihnk::think
:*:impor t::import{Space}
:*:rebas e::rebase{Space}
:*?:ocmment::comment
:*?:particualr::particular
:*?:deifne::define
:*?:ocmpare::compare
:*?:compalins::complains
:*?:recommentat::recommendat
:*?:optoinal::optional
:*?:extesion::extension
:*?:ptoin::ption
:*?:mananger::manager
:*?:temri::termi
:*?:esatbl::establ
:*?:incresa::increas
:*?:striclty::strictly
:*?:reposnb::responsib
:*?:thgouth::thought
:*?:tghouth::thought
:*?:thgought::thought
:*?:copmlain::complain
:*?:accomod::accommod
:*?:reposiory::repository
:*?:recommencat::recommendat
::aidit::audit
:*?:matadata::metadata
:*?:remakr::remark
::juts::just
:?*:youself::yourself
:*?:developement::development
:*?:jyust::just
:*?:juyst::just
:*?:tohught::thought
:*?:misisng::missing
:*?:easilty::easilty
:*?:waitinf::waiting
:*?:intenral::internal
:*?:hedaer::header
::clinet::client
:*?:prims::prism
:*?:sh9op::shop
:*?:sho9p::shop
:*?:elemnet::element
:*?:elkeme::eleme
:*?:ensiosn::ensions

; ? (question mark): The hotstring will be triggered even when it is inside another word; that is, when the character typed immediately before it is alphanumeric. 
; * (asterisk):      An ending character (e.g. Space, ., or Enter) is not required to trigger the hotstring


; not typos, but for ease of use
:*?:*-)::🤔
:*?:(a)::😇
:*?::wip::🚧
:*?::expressionless::😑
:*?::shrug::🤷‍♂️
:*?::euro::€
:*?::paragraph::§
:?*:\+-::±
:?*:\-+::∓
:?*:\approx::≈
:?*:\paragraph::§
; programming
:*?:yarn linkt::yarn link
:*?:npm run install::npm install
:*?:docker build and run::docker run -it $(docker build -q .)
:?*:source venv::source venv/Scripts/activate
:?*:source /venv::source /venv/bin/activate
:*:parquest::parquet
:*?:git yarn::yarn
:*?:gitp ul::git pul
:*?:poetry run flight server::STORAGE_PATH=TMP poetry run python -m tests.arrow.server
:*?:poetry activate::deactivate; source "$(dirname $(poetry run which python))/activate"
:*?:poetry clean::poetry env remove "$(which python | head -n 1)" && poetry install && source "$(dirname $(poetry run which python | head -n 1))/activate"
:*?:gihub::github
:*?:git assimilate typings::git assimilate typings -- connector/typings/**
:*?:~./bashrc::~/.bashrc
:*?:~/.,bashrc::~/.bashrc
:*?:~/,.bashrc::~/.bashrc
:*?:pytest int::INTEGRATION_TESTS=true pytest .
:*?:int pytest::INTEGRATION_TESTS=true pytest .
; :?:pylint::black .{ENTER}flake8{ENTER}mypy{ENTER}INTEGRATION_TESTS=true pytest .{ENTER}  should be a script instead that stops when one fails
:*?c:opentel::opentelemetry
:*?c:openTel::OpenTelemetry
:*?c:OpenTel::OpenTelemetry
:*?c:OpenTEl::OpenTelemetry
:*?:falke8::flake8
:?*:lfake8::flake8
:*?:git merge main::git fetch && git merge -m "Merge 'main'" origin/main
:*?:git merge master::git fetch && git merge -m "Merge 'master'" origin/master
:?*:git reset --hard origin/::git fetch && git reset --hard "origin/$(git rev-parse --abbrev-ref HEAD)"
:?:git reset --hard origin::git fetch && git reset --hard "origin/$(git rev-parse --abbrev-ref HEAD)"
:*?:gh auth login::gh auth login --with-token <<< $(cat $HOME/.ssh/gh_token)
:*?:ulogn::ulong
:*?:uylong::ulong
:*?:poetry where::dirname $(poetry run which python)
:*?:git pull -p::git pull -p && git prune-locally
:*?:git fetch -p::git fetch -p && git prune-locally
:*?:argo apply::argo submit
:*?:glcoud::gcloud
:*?:pytes t::pytest{Space}
:*?:psycogp::psycopg
:*?:npm lint::npm{Space}run{Space}lint
:*?:git reset main::git reset $(git merge-base HEAD main)
:*?:npm ru n::npm run{Space}
:*?:uwnip::unwip
:?:giut::git

; Norwegian
:*?:fodels::fødsels
:*?:fodsels::fødsels
:?c:Bodo::Bodø
::tromso::Tromsø
:*?:sor-ost::Sør-Øst

; Dutch
::neit::niet
:c:Begum::Begüm
::misshcien::misschien

; Miscellaneous
#+PrintScreen::Send #+s ; #+s maps to the Windows screen snipping tool
RControl & PgDn::Send {RControl Down}#{Right}{RControl Up}  ; enable one-handed desktop swapping
RControl & PgUp::Send {RControl Down}#{Left}{RControl Up}   ; enable one-handed desktop swapping
#^PgDn:: Send #^{Right}
#^PgUp:: Send #^{Left}
:*?:jbsnoror::jbsnorro
:c*:JBSN::JBSn
:c*:JBsn::JBSn
:*?:jbanorro::jbsnorro
:*?:jerone::jeroen


; greek

::\alpha::α
::\beta::β
::\gamma::γ
::\Gamma::Γ
::\Delta::Δ
::\delta::δ
::\epsilon::ε
::\eta::η
::\theta::θ
::\Theta::Θ
::\iota::ι
::\kappa::κ
::\Lambda::Λ
::\lambda::λ
::\Zeta::Ζ
::\zeta::ζ
::\mu::μ
::\nu::ν
::\pi::π
::\Pi::Π
::\rho::ρ
::\tau::τ
::\xi::ξ
::\Xi::Ξ
::\Upsilon::Υ
::\upsilon::υ
::\Phi::Φ
::\phi::φ
::\Chi::Χ
::\chi::χ
::\Psi::Ψ
::\psi::ψ
::\Omega::Ω
::\omega::ω
::\sigma::σ
::\Sigma::Σ

